version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - npm ci

    build:
        commands:
            - npm run build -- --configuration production

artifacts:
    files:
        - dist/booster-ng/**/*       # Tu build Angular
        - appspec.yml                # Necesario para CodeDeploy
        - scripts/**/*               # Scripts de hooks (restart apache, etc.)
